apiVersion: batch/v1
kind: Job
metadata:
  name: local-app
  labels:
    app: medicine-tracker       # Global label for the whole project
    component: local-app        # Component-specific label
spec:
  template:                     # Defines the pod template
    metadata:
      labels:
        app: medicine-tracker
        component: local-app
    spec:
      containers:
        - name: local-app
          image: personalmedicinetracker-local-app
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: aws-credentials
          # volumeMounts:
          #   - name: csv-volume
          #     mountPath: /app/medicines_inventory.csv   # Mount path inside container
          #     subPath: medicines_inventory.csv         # Mount only this file from PVC
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "600m"

      restartPolicy: Never

      # volumes:
      #   - name: csv-volume
      #     persistentVolumeClaim:
      #       claimName: medicines-pvc  # Reference to the shared PVC with CSV
