FROM python:3.11-slim

WORKDIR /app

# Copy requirements from docker folder
COPY docker/docker_local/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy only specific files
COPY medicineChildLocal.py /app/
COPY medicineParent.py /app/

# Copy the CSV directly into /app
COPY medicines_inventory.csv /app/medicines_inventory.csv

# Set env variable for CSV path
ENV INVENTORY_CSV=/app/medicines_inventory.csv

CMD ["python", "medicineChildLocal.py"]
