FROM python:3.11-slim

WORKDIR /app

# Copy requirements from docker folder
COPY docker/docker_Messages/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy only specific files
COPY medicineDB.py /app/
COPY medicineEmailsAndMessages.py /app/


CMD ["python", "medicineEmailsAndMessages.py"]
