
services:
  messages-app:
    build:
      context: .
      dockerfile: docker/docker_Messages/Dockerfile.messages
    container_name: messages-app-container  
    env_file:
      - .env 
    restart: "no"  
    

  lambda-app:
    build:
      context: .
      dockerfile: docker/docker_lambda/Dockerfile.lambda
    container_name: lambda-app-container  
    env_file:
      - .env  
    restart: "no"  

  cloud-app:
    build:
      context: .
      dockerfile: docker/docker_cloud/Dockerfile.cloud
    container_name: cloud-app-container  
    env_file:
      - .env
    restart: "no"  

  mysqldb-app:
    build:
      context: .
      dockerfile: docker/docker_mysql/Dockerfile.mysql
    container_name: mysqldb-app-container  
    ports:
      - "3307:3306"  
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: "no"

volumes:
  mysql-data: