
services:
  local-app:
    build:
      context: .
      dockerfile: docker/docker_local/Dockerfile.local
    env_file:
      - .env 
    container_name: local-app-container

  lambda-app:
    build:
      context: .
      dockerfile: docker/docker_lambda/Dockerfile.lambda
    env_file:
      - .env  
    container_name: lambda-app-container

  cloud-app:
    build:
      context: .
      dockerfile: docker/docker_cloud/Dockerfile.cloud
    env_file:
      - .env  
    container_name: cloud-app-container
