apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql       # local path on node (for dev/minikube)
  persistentVolumeReclaimPolicy: Retain
