FROM python:3.11-slim

WORKDIR /app

# Copy requirements from docker folder
COPY docker_local/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy only specific files
COPY medicineChildLocal.py /app/
COPY medicineParent.py /app/



CMD ["python", "medicineChildLocal.py"]
