# Use base image for Python 3.11-slim
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy dependency list
COPY docker/docker_cloud/requirements.txt /app/requirements.txt

# Install dependencies into the image
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code into the image
COPY medicineDB.py /app/
COPY medicineEmailsAndMessages.py /app/
COPY medicineCloud.py /app/


# Run the main script
CMD ["python", "medicineCloud.py"]
